export const ACTION_TYPE = {
  INITIALIZE_CATEGORIES: "INITIALIZE_CATEGORIES",
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  CLEAR_FILTER: "CLEAR_FILTER",
  SORT_BY: "SORT_BY",
  SORT_BY_RATING: "SORT_BY_RATING",
  PRICE_RANGE: "PRICE_RANGE",
  CATEGORY: "CATEGORY",
};
