export const ACTION_TYPE = {
  INITIALIZE_CATEGORIES: "INITIALIZE_CATEGORIES",
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  CLEAR_FILTER: "CLEAR_FILTER",
  SORT_BY: "SORT_BY",
  SORT_BY_RATING: "SORT_BY_RATING",
  PRICE_RANGE: "PRICE_RANGE",
  CATEGORY: "CATEGORY",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_QTY_IN_CART: "UPDATE_QTY_IN_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};
